server:
  port : 8081
eureka:
  instance:
    hostname: localeurekaclient.herokuapp.com
  client:
    serviceUrl:
      defaultZone: https://localeurekaserver.herokuapp.com/eureka/
spring:
  application:
    name: micro-app-eureka-client