server:
  port : ${PORT:8081}
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: https://localeurekaserver.herokuapp.com/eureka/
spring:
  application:
    name: micro-app-eureka-client